server:
  port: 8083
  servlet:
    context-path: /vct-ws


spring:
  # 数据库
  datasource:
    name: test
    url: jdbc:mysql://rm-j6cit0g68k742p9u7.mysql.rds.aliyuncs.com:3306/vct?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: bibao
    password: Bibao!#%&()
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #初始化连接数
      initial-size: 5
      #最大连接数
      max-active: 100
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #最小连接数量
      min-idle: 5
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      pool-prepared-statements: false
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: 100
      #用来检测连接是否有效的sql，要求是一个查询语句。
      validation-query: select 1
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #1.Destroy线程会检测连接的间隔时间 2.testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
      filters: stat
  # redis缓存数据库配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 172.31.64.210
    port: 6379
    password: erguergu
    # 连接超时时间（毫秒）
    timeout: 10000s
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10s

  #类管理工具
  jmx:
    default-domain: vct-ws


mybatis:
  #pojo扫描的包名
  type-aliases-package: com.ergu.vctwebsocket.pojo
  #Mapper.xml所在的位置
  mapper-locations: classpath:mapper/**/*Mapper.xml
  #字段转换实体类驼峰式命名
  configuration:
    map-underscore-to-camel-case: true
    # 解决map对象转出为null 不输出字段
    call-setters-on-nulls: true


#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  #false禁用分页合理化
  reasonable: false
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql


#日志
logging:
  config: classpath:logback-spring.xml